#!/bin/sh

# Display settings
export DISPLAY=:0
systemctl --user import-environment DISPLAY

# xdg-desktop-portal
systemctl --user start xdg-desktop-portal-gtk
systemctl --user start xdg-desktop-portal

# DPI
xrdb -merge ~/.config/X11/Xresources 

# Keyboard
xset r rate 200 30 & 

# Programs 
dunst & 
sxhkd &
lxsession & 
flameshot &

# numlock
numlockx & 

# Wallpaper
feh --no-fehbg --randomize --bg-fill ~/Pictures/Wallpapers

# Scripts
exec ~/.local/bin/nvidia_powerlevel.sh &
exec ~/.local/bin/auto-sort.sh &

# compositor
picom & 

# Lockscreen
# betterlockscreen &

# dwm
exec ~/.local/bin/dwmstart.sh
